In [1]:
import pandas as pd

# Creating the DataFrame with fixed, non-random data
data_fixed = {
    "Feature1": [61, 24, 81, 70, 30],
    "Feature2": [49.610578, 30.874075, 30.582658, 0.353315, 1.153121],
    "Feature3": [2, 9, 5, 2, 4],
    "Target": [1, 1, 1, 1, 0]
}

df = pd.DataFrame(data_fixed)

df


Feature1   Feature2  Feature3  Target
0        61  49.610578         2       1
1        24  30.874075         9       1
2        81  30.582658         5       1
3        70   0.353315         2       1
4        30   1.153121         4       0

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import numpy as np
# Splitting the data
X = df[["Feature1", "Feature2", "Feature3"]]
y = df["Target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Applying MinMaxScaler
scaler = MinMaxScaler()

# Fit the scaler on the training data only
X_train_scaled = scaler.fit_transform(X_train)

# Transform the test data using the scaler fitted on training data
X_test_scaled = scaler.transform(X_test)

print(np.array(X_train))
X_train_scaled


[[61.       49.610578  2.      ]
 [30.        1.153121  4.      ]
 [81.       30.582658  5.      ]
 [24.       30.874075  9.      ]]


array([[0.64912281, 1.        , 0.        ],
       [0.10526316, 0.        , 0.28571429],
       [1.        , 0.60732731, 0.42857143],
       [0.        , 0.61334118, 1.        ]])

In [3]:
X_test_scaled

array([[ 0.80701754, -0.01650532,  0.        ]])

In [7]:
import numpy as np
data = [
    [61.,49.610578,2.],
 [30.,1.153121,4.],
 [81.,30.582658,5.],
 [24.,30.874075,9.]
 ]
type(data)

list

In [6]:
#final_test = data.reshape(1, -1)

# Transform the input using the scaler
final_test_scaled = scaler.transform(data)
final_test_scaled

c:\Users\Dileep Sathya\OneDrive\Desktop\MLOPS\first_end_to_end_ML\venv\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.64912281, 1.        , 0.        ],
       [0.10526316, 0.        , 0.28571429],
       [1.        , 0.60732731, 0.42857143],
       [0.        , 0.61334118, 1.        ]])